version: '3.8'

networks:
  default:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro  # Mount Let's Encrypt certificates
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      openhands:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.29
    ports:
      - "3000:3000"
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.29-nikolaik
      - LOG_ALL_EVENTS=true
      - LOG_LEVEL=debug
      - RUNTIME_INIT_TIMEOUT=120
      - RUNTIME_MAX_CONCURRENT=2
      - RUNTIME_HOST=172.17.0.1
      - RUNTIME_SERVER_HOST=172.17.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: unless-stopped
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G 