version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: ayacoder-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro  # Mount Let's Encrypt certificates
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - openhands
    restart: unless-stopped
    networks:
      ayacoder:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.29
    container_name: ayacoder-openhands
    ports:
      - "3000:3000"
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.29-nikolaik
      - LOG_ALL_EVENTS=true
      - LOG_LEVEL=debug
      - RUNTIME_INIT_TIMEOUT=120
      - RUNTIME_MAX_CONCURRENT=2
      - HOST_DOCKER_INTERNAL=172.20.0.1
      - RUNTIME_DOCKER_NETWORK=ayacoder
      - RUNTIME_DOCKER_HOST=unix:///var/run/docker.sock
      - RUNTIME_SERVER_HOST=172.20.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
    restart: unless-stopped
    networks:
      ayacoder:
        ipv4_address: 172.20.0.3
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:172.20.0.1"

networks:
  ayacoder:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 