version: '3.8'

networks:
  openhands-network:
    driver: bridge
    # Not making it internal so the ports can be accessed
  nginx-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro  # Mount Let's Encrypt certificates
      - ./htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      openhands:
        condition: service_healthy
    networks:
      - nginx-network
      - openhands-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.29
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.29-nikolaik
      - LOG_ALL_EVENTS=true
      - RUNTIME=docker
      - RUNTIME_INIT_TIMEOUT=60
      - RUNTIME_DOCKER_NETWORK=openhands-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - openhands-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G 